---
version: "3"
services:
 devopsdb:
   image: siacharan/nandu:dbimage
   ports:
     - "3306:3306"
   

 application:
   image: siacharan/nandu:appimage
   ports:
     - "1111:8080"
   deploy:
       replicas: 3
   depends_on:
     - "devopsdb"
