---
version: "3"
services:
 devopsdb:
 deploy:
    replicas: 2
   image: siacharan/mymenu:dbimage
   ports:
     - "3306:3306"

 application:
   image: siacharan/mymenu:appimage
   deploy:
     replicas: 3
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
