---
version: "3"
services:
 devopsdb:
 deploy:
    replicas: 3
   image: shaikmustafa/siacharan:dbimage
   ports:
     - "3306:3306"

 application:
   image: shaikmustafa/siacharan:appimage
   deploy:
      replicas: 2
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
